# Generated by Django 6.0 on 2026-03-18 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('DATA_OWNER', 'Data Owner'), ('RESEARCHER', 'Researcher'), ('ADMIN', 'Admin')], default='DATA_OWNER', max_length=20),
        ),
    ]
