# Generated by Django 5.2.12 on 2026-03-30 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_alter_computation_options_alter_computation_dataset_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN_SUCCESS', 'Login Success'), ('LOGIN_FAILED', 'Login Failed'), ('LOGOUT', 'Logout'), ('REGISTER', 'User Registered'), ('ACCOUNT_LOCKED', 'Account Locked'), ('ACCOUNT_UNLOCKED', 'Account Unlocked'), ('DATASET_UPLOAD', 'Dataset Uploaded'), ('DATASET_PROCESS', 'Dataset Processed'), ('DATASET_DELETE', 'Dataset Deleted')], db_index=True, max_length=50),
        ),
    ]
