# Generated by Django 5.2.12 on 2026-04-17 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN_SUCCESS', 'Login Success'), ('LOGIN_FAILED', 'Login Failed'), ('LOGOUT', 'Logout'), ('REGISTER', 'User Registered'), ('ACCOUNT_LOCKED', 'Account Locked'), ('ACCOUNT_UNLOCKED', 'Account Unlocked'), ('DATASET_UPLOAD', 'Dataset Uploaded'), ('DATASET_PROCESS', 'Dataset Processed'), ('DATASET_DELETE', 'Dataset Deleted'), ('ACCESS_DENIED', 'Access Denied')], db_index=True, max_length=50),
        ),
    ]
